# Generated by Django 4.2.6 on 2023-10-30 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.coursesection'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.UUID('2b5bd526-137f-40fb-9b07-84bc440b87dd'), unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episode',
            field=models.ManyToManyField(blank=True, to='courses.episode'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.UUID('34837130-b791-4dbd-b0f3-49f4cdaf63ca'), unique=True),
        ),
    ]
