# Generated by Django 4.2.6 on 2023-10-30 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_section_alter_course_course_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.comments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.UUID('fc90cc7c-16b4-49f7-b0e6-18a947ff9a95'), unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.UUID('7871e4fc-1966-4b37-849a-e5bd7cb26d36'), unique=True),
        ),
    ]
